#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be
# 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#Let us list the factors of the first seven triangle numbers:
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
#10: 1,2,5,10
#15: 1,3,5,15
#21: 1,3,7,21
#28: 1,2,4,7,14,28
#We can see that 28 is the first triangle number to have over five divisors.
#What is the value of the first triangle number to have over five hundred divisors?

#126615th place! 

require_relative 'glad_colors'
def triNum(n)
  sum = 0
  (1..n).each { |n| sum += n }
  return sum
end

def factors(num)
  array = []
  if ( num == 1 )
    array.push(1)
  end
  
  denominator = 1
  max = num
  while (denominator <= max)
     if ( num % denominator == 0 )
       array.push(denominator)
       subfac = num/denominator      
       if ( denominator != subfac )
         array.push(subfac)
       end
       max = subfac
     end
     denominator += 1
   end
   return array
 end
 
 index = 1
 while(factors(triNum(index)).length < 500)
   index += 1
 end
 
 puts "You answer: " + pink(triNum(index)) + ". If you like it so much why don't you marry it? " \
 + pink("Well, I won't let you!")

